### ISSUE TITLE
Unable to resolve host "enduser-sdk.circle.com": No address associated with hostname

### ISSUE THREAD

**Issue by chiemezie1** [circlefin/w3s-android-sample-app-wallets#32]
<img width="349" alt="Screenshot 2023-11-19 194903" src="https://github.com/circlefin/w3s-android-sample-app-wallets/assets/106808580/4b2cadf9-db26-4bad-9b7c-6c3d4a5263cc">

**Comment by Spacekase32** [comment]
Try it in desktop mode if ur on android

**Comment by chiemezie1** [comment]
Thanks it worked

**Comment by Spacekase32** [comment]
Glad to hear it!

Kasey Johnson 3:41 12/13/2023
